# Generated by Django 2.1.7 on 2019-03-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190228_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created',
            new_name='updated',
        ),
    ]
